### ISSUE TITLE
Avatar command errors when no user is mentioned

### ISSUE THREAD

**Issue by NatsumiHB** [Dragory/ZeppelinBot#105]
According to the code, [the avatar command should assume `msg.author` if no user is given](https://github.com/Dragory/ZeppelinBot/blob/49d965a61d03032370194c7fedb21b3f554571f0/backend/src/plugins/Utility/commands/AvatarCmd.ts#L17). However, when trying to invoke the avatar command without any arguments you are greeted with this:
```
Missing required argument: user
Usage: !!avatar <user>
```

**Comment by Dragory** [comment]
Thank you for catching that! The fix should be included in an update in the near future.
