### ISSUE TITLE
I dont know what to fill in for the .env things.

### ISSUE THREAD

**Issue by Curioo** [Dragory/ZeppelinBot#117]
Can anyone help me / give me tips on what to fill in for each field and what format to use?
I know there is no support provided, but i thought the community could give me a hand here :)

**Comment by aditya-learns** [comment]
Google up what is env

**Comment by Dragory** [comment]
This issue tracker should primarily be used for issues regarding Zeppelin development. If you'd like to ask the community for help regarding self-hosting, feel free to join the Discord server instead: https://discord.com/invite/w8njuNu

**Comment by AleksanderPVP** [comment]
comment
