### ISSUE TITLE
Include sticker info in !source

### ISSUE THREAD

**Issue by vcokltfre** [Dragory/ZeppelinBot#237]
Currently, the `source` command works with message ID, content, attachments, and embeds, but not stickers (which are of course now released for custom uploading), so I think that should also be supported.

Example:
```json
{
  "id": "859858669486342176",
  "content": "",
  "attachments": [],
  "embeds": [],
  "stickers": {
    "id": "1234",
    "name": "pogcow"
  }
}
```

**Comment by DarkView** [comment]
This will be part of my djs rework once [this PR](https://github.com/discordjs/discord.js/pull/5867) is merged :)

**Comment by vcokltfre** [comment]
Awesome!
