### ISSUE TITLE
No license.txt

### ISSUE THREAD

**Issue by Heath123** [Dragory/ZeppelinBot#65]
What's the license for this project? There's no license.txt...
https://choosealicense.com/no-permission/

**Comment by almeidx** [comment]
https://github.com/Dragory/ZeppelinBot/blob/master/assets/icons/LICENSE

**Comment by Dragory** [comment]
There is no license for the project. Zeppelin is "source available", but not open source.

**Comment by Heath123** [comment]
From that link, it seems like you might want some license, even if it's a restrictive/custom one?
